In [1]:
import numpy as np

In [2]:
'''
1. Create a numpy arrays of shape (3,) and concatenate across the column axis?
'''
x = np.array([1,2,3]).reshape((3,1))
y = np.array([4,5,6]).reshape((3,1))
x = np.concatenate((x,y),axis = 0)
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [3]:
'''
2. Create a random numpy array of shape (50,) and filter out negative values?
'''
x = np.random.random(50)
filtered_x = x[x >= 0]
filtered_x

array([0.90057031, 0.31776891, 0.39700678, 0.07588772, 0.73482808,
       0.25968885, 0.24337174, 0.93020132, 0.1180659 , 0.54003688,
       0.66904648, 0.56805535, 0.34274545, 0.31933837, 0.84176701,
       0.85456536, 0.9811115 , 0.09348364, 0.56420678, 0.42969495,
       0.92231733, 0.86632402, 0.76439467, 0.29466599, 0.2692156 ,
       0.57368998, 0.64284535, 0.24437478, 0.93950127, 0.88224374,
       0.49830435, 0.17183691, 0.1316992 , 0.44237871, 0.52984153,
       0.39847784, 0.30794472, 0.96032004, 0.20614416, 0.07986988,
       0.12940208, 0.03926284, 0.74294527, 0.2777617 , 0.605681  ,
       0.40787896, 0.45811602, 0.03881655, 0.7415064 , 0.01770866])

In [4]:
'''
3. Create a random integer array of shape (100,) and normalize it?
'''
x = np.random.randint(1,100,size=100)
mean_x = np.mean(x)
centered_x = x-mean_x
std_x = np.std(x)
final_x = centered_x/std_x
x_final_mean = np.mean(final_x)
x_final_mean

-8.43769498715119e-17

In [5]:
'''
4. Create a random numpy array of shape (20,) and find mean, median, and mode?
'''
x = np.random.random(20)
mean_x = np.mean(x)
mean_x

0.4163586537571674

In [6]:
median_x = np.median(x)
median_x

0.29396209863521666

In [7]:
mode_x = np.max(x)
mode_x

0.9513423184388788

In [8]:
from scipy import stats
mode_x = stats.mode(x)
mode_x

ModeResult(mode=0.0374083357189251, count=1)

In [9]:
'''
5. Create a numpy array of shape (40,) and reshape it to (8,5)?
'''
x = np.random.randint(1,40,size=40).reshape((8,5))
x

array([[20, 19, 17,  5,  2],
       [ 5, 30, 30, 15,  7],
       [15, 32, 20, 36, 17],
       [26,  9, 16, 15, 13],
       [31, 38, 17, 23, 31],
       [ 9, 39, 11, 39, 37],
       [39,  4, 21, 35,  6],
       [36, 21, 37,  9, 27]])

In [10]:
'''
6. Create a random numpy matrix of shape (4,6) and
   extract 2nd row and 3 column values?
'''
x = np.random.randint(0,30,(4,6))
x

array([[22, 25,  6,  7,  6,  0],
       [ 0, 23, 26,  4, 24, 28],
       [23, 26, 26, 20, 18, 25],
       [ 8, 28, 29, 12, 23,  1]])

In [11]:
x[1, :]


array([ 0, 23, 26,  4, 24, 28])

In [12]:
x[:,2]

array([ 6, 26, 26, 29])

In [13]:
'''
7.Create a random int numpy array of shape(100,) and
   find the position of the maximun value?
'''
x = np.random.randint(0,100,100)
x = np.argmax(x) #or x.argmax()
x

55

In [14]:
'''
8. Create two numpy array of shape (2,3) and(1,3) and
    then perform a vertical stack?
'''
x = np.random.randint(0,20,(2,3))
y = np.random.randint(21,40,(1,3))
x = np.vstack((x,y))
x

array([[13,  8, 11],
       [ 9,  9,  3],
       [24, 22, 37]])

In [15]:
'''
9. Write a program to import numpy array and print the version?
'''
import numpy as np
np.__version__

'1.23.5'

In [16]:
'''
10. Create a random numpy array of shape (20,30) and perfrom vertical split
    into 4 matrices?
'''
x = np.random.random((20,30))
x = np.vsplit((x), 4)
x

[array([[0.84610119, 0.22080489, 0.30028342, 0.19300301, 0.76341585,
         0.50044234, 0.67166687, 0.22634578, 0.96116909, 0.9142223 ,
         0.59130018, 0.8253737 , 0.77626407, 0.960416  , 0.05632004,
         0.48225462, 0.96462667, 0.57330589, 0.22713694, 0.26282107,
         0.95184109, 0.6294089 , 0.81635655, 0.80318505, 0.4186489 ,
         0.62543364, 0.64062267, 0.59568906, 0.68172242, 0.7438241 ],
        [0.42167337, 0.38110448, 0.04423985, 0.54138177, 0.95300155,
         0.31997732, 0.5737257 , 0.13285755, 0.23013804, 0.28966111,
         0.10569145, 0.23289581, 0.53325455, 0.22726585, 0.24110463,
         0.81535377, 0.74178941, 0.53816962, 0.24333122, 0.62272133,
         0.74125935, 0.14320567, 0.91317842, 0.44364872, 0.4236296 ,
         0.34810914, 0.874052  , 0.86877494, 0.54892302, 0.59489326],
        [0.57486501, 0.90372996, 0.79533755, 0.13831481, 0.78236466,
         0.88861699, 0.47171502, 0.50047093, 0.54068533, 0.04775929,
         0.59758147, 0.02439713,

In [17]:
'''
11. Create a numpy array of shape(3,) and find the shape, ndim and reshape it
     to (3,1)?
'''
x = np.array([1,2,3])

In [18]:
x.shape

(3,)

In [19]:
np.ndim(x) # or - x.ndim

1

In [20]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [21]:
'''
12. Create a numpy array of shape (2,3) and convert it into (2,1,3)?
'''
x =  np.array([[2,3,4],[2,3,4]])


In [22]:
x.shape

(2, 3)

In [23]:
y = x[:,np.newaxis,:].shape
y

(2, 1, 3)

In [33]:
'''
13. Write a python code to create a list of numbers from 1 to 20 and convert them
    into two numpy arrays containing even and odd numbers?
'''
list1 = [i for i in range(1,20)]
b = np.array(list1)
x = b[b %2 == 0]
print("Even = ", x )
y = b[b % 2 != 0]
print("Odd = ",y)

Even =  [ 2  4  6  8 10 12 14 16 18]
Odd =  [ 1  3  5  7  9 11 13 15 17 19]


In [37]:
'''
14. Create a random numpy array of shape (8,10) and
    find the total numpy of values greater than 0.5?
'''
x = np.random.random((8,10))
print('x = ',x)
y = x[x > 0.5]
print('Y =', y)

x =  [[0.59334927 0.41625982 0.4482092  0.20088134 0.60496554 0.26297282
  0.81741087 0.08561065 0.47060349 0.48880208]
 [0.57040271 0.03742014 0.99495357 0.38798735 0.37647354 0.28316477
  0.66988299 0.97488753 0.98057541 0.03738001]
 [0.2950434  0.33637503 0.95314943 0.23481431 0.23406043 0.58737983
  0.51999831 0.38295008 0.22455031 0.88027562]
 [0.63577424 0.02174814 0.55303254 0.41815525 0.75193032 0.52752531
  0.98193643 0.77340645 0.15408743 0.86097837]
 [0.20288086 0.0055934  0.2200369  0.30048085 0.27459252 0.36176409
  0.01517693 0.14857671 0.9735505  0.67279261]
 [0.17769716 0.22620967 0.87013355 0.68592935 0.83236084 0.55897224
  0.12438469 0.06942819 0.32417212 0.5821874 ]
 [0.01793936 0.78825742 0.07163323 0.70968892 0.01467387 0.70395847
  0.23427401 0.46275785 0.54173747 0.12809021]
 [0.0737083  0.11769641 0.7660469  0.02690209 0.80416507 0.08679103
  0.75897514 0.64686445 0.1229071  0.54919466]]
Y = [0.59334927 0.60496554 0.81741087 0.57040271 0.99495357 0.66988299
 0.