NumPy - Basics

In [ ]:
# NumPy stands for numerical python.
# It is a python library used for working wiht an array.
# An array is a data structure that stores values of same type.

In [2]:
import numpy as np # aliasing - giving another name to existing object

In [4]:
# version
np.__version__

'1.23.5'

In [5]:
l1 = [i for i in range(10)]

In [6]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(l1)

list

In [8]:
np.array(l1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.array([1,2,3,4],dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [11]:
# Declaring a matrix in 3*3
np.array([[2,3,4],[5,6,7],[8,9,10]])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [14]:
# To declare as all 10 zeros
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
#similarlly to declare as all ones
# but here it's about shape, so apply tuple always to get matrix
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
#linear spacing
np.linspace(0,1,5) #(start,end,count)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
# To generate random
np.random.random((3,3))

array([[0.20784178, 0.77506126, 0.0092681 ],
       [0.51127322, 0.28551711, 0.09732369],
       [0.64993931, 0.6697042 , 0.95899747]])

In [26]:
'''
class numpy -- parent class
class random -- child class

  def random

  def randint

  def normal
'''
# TO generate random int between certain range
np.random.randint(0,10,(3,3))

array([[4, 5, 4],
       [6, 0, 9],
       [0, 9, 9]])

In [22]:
# To enerate identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# or
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
x1 = np.random.randint(0,10,size=6)
x2 = np.random.randint(0,10,size=(3,4))
x3 = np.random.randint(0,10,size=(3,4,5))

In [32]:
x1

array([5, 0, 7, 4, 5, 4])

In [33]:
x2

array([[6, 3, 7, 8],
       [2, 5, 7, 6],
       [6, 2, 1, 6]])

In [34]:
x3

array([[[7, 4, 7, 3, 6],
        [3, 5, 7, 9, 3],
        [7, 7, 8, 6, 1],
        [1, 0, 0, 7, 5]],

       [[3, 0, 6, 6, 1],
        [4, 0, 5, 2, 8],
        [2, 5, 9, 7, 7],
        [5, 6, 6, 2, 7]],

       [[9, 4, 3, 5, 2],
        [6, 7, 3, 1, 5],
        [1, 9, 8, 1, 8],
        [5, 2, 4, 1, 3]]])

In [35]:
# to check the dimension of a array
x3.ndim

3

In [36]:
x2.ndim

2

In [37]:
x1.ndim

1

In [38]:
# to find the shape of a perticular matrix or tensile, or vector
x1.shape

(6,)

In [39]:
x2.shape

(3, 4)

In [40]:
x3.shape

(3, 4, 5)

In [41]:
x3.size

60

In [43]:
# To access the perticular element
x1[4]

5

In [45]:
x1[-1]

4

In [46]:
x2[2]

array([6, 2, 1, 6])

In [48]:
x2[-2]

array([2, 5, 7, 6])

In [50]:
x2

array([[6, 3, 7, 8],
       [2, 5, 7, 6],
       [6, 2, 1, 6]])

In [49]:
#[rowindwx,columnindex]
x2[0,0]

6

In [51]:
# to change the elements
x2[0,0] = 12

In [52]:
x2

array([[12,  3,  7,  8],
       [ 2,  5,  7,  6],
       [ 6,  2,  1,  6]])

In [53]:
x2[2,2] = 4

In [54]:
x2

array([[12,  3,  7,  8],
       [ 2,  5,  7,  6],
       [ 6,  2,  4,  6]])